react-native-image-picker/react-native-image-picker

- README.md
My XCode adds as a Folder reference rather than Group reference which stops the file from being added to `Compile Sources`
Just a warning added to the instructions so XCode newbies (like myself) know to look out for this.
related to [issue #18](https://github.com/marcshilling/react-native-image-picker/issues/18)
> Update Install directions

- UIImagePickerManager/UIImagePickerManager.m
Add option for custom buttons on action sheet. (ex: "Edit Image Selection")
```js
var ImgOptions = {
title: 'Select Photo',
cancelButtonTitle: 'Cancel',
takePhotoButtonTitle: 'Take Photo...',
takePhotoButtonHidden: false,
chooseFromLibraryButtonTitle: 'Choose from Library...',
chooseFromLibraryButtonHidden: false,
returnBase64Image: true,
returnIsVertical: false,
customButtons: {
"Edit Image Selection...": "edit",
},
quality: 0.2
};
\\...
UIImagePickerManager.showImagePicker(ImgOptions, (type, response) => {
if (type == 'edit') {
\\...
```
> Update UIImagePickerManager.m - add option for custom buttons in action sheet

- UIImagePickerManager/UIImagePickerManager.m
While testing on the simulator this was not working. It looks like the iPad uses an alert view instead of action sheet. Changed from using clickedButtonAtIndex to didDismissWithButtonIndex. This fixed the problem.
Tests performed:
Not in modal on iPhone: pass
In modal on iPhone: pass
Not in modal on iPad: pass
In modal on iPad: FAILED (also failed before this change)
Also found this article: http://stackoverflow.com/questions/25510894/prevent-my-ios-8-ipad-actionsheet-from-dismissing-its-parent-viewcontroller
"Moving forward you should embrace UIAlertController."
> Fix presentation on iPad

- UIImagePickerManager/UIImagePickerManager.m
Add storageOptions to allow saving to a path in the documents directory instead of tmp (which can get cleared).
```js
var options = {
title: 'Select Photo',
cancelButtonTitle: 'Cancel',
takePhotoButtonTitle: 'Take Photo...',
takePhotoButtonHidden: false,
...
storageOptions: { // if this is provided image will get saved in the documents directory
skipBackup: true, // will set attribute so the image is not backed up by icloud
path: "images", // save in a sub directory in documents instead of root
},
...
```
> Add option to save image to documents dir

- Android/src/main/java/com/imagepicker/ImagePickerModule.java
- README.md
- package.json
Hello, me again !
- cancelButtonTitle
- takePhotoButtonTitle
- chooseFromLibraryButtonTitle
- noData
(same usage as iOS)
- isVertical
- width
- height
(same as iOS)
- on BACK key press and on touch outside the dialog => the callback will be called with a didCancel true
I add a table to the readme.md to show supported options for iOS and for Android, and also clarified Android and iOS part
I also set the version to 0.9.1, it would be awesome to publish this version if you are willing to merge it !
NOTE : Just don't merge it right now, i'm currently working on maxWidth et maxHeight (just see that it was really usefull after pr ahah)
> Add android options/response

- Android/src/main/java/com/imagepicker/ImagePickerModule.java
After updating our legacy version of react-native-image-picker in order to make it work on Android, it broke because I was specifying ```title: null``` which caused an error on Android. Since it still says in the README that ```title: null``` is supported, I just created this little patch.
> Allow null value for title option

- README.md
- UIImagePickerManager/UIImagePickerManager.m
- package.json
Initial support for recording video or picking videos from the image picker. The code now looks for 'mediaType' to determine if it should take a 'photo' or a 'video'.
Added code to use the option key 'qualityType' to set 'high', 'medium' and 'low' image quality settings. Defaults to 'medium'.
Added code to check the option key 'imageFileType'. imageFileType === 'png' exports the photo as PNG instead of JPG. Defaults to JPG if imageFileType is not set or if set to any value other than 'png'.
Added some error reporting when some steps fail, rather than just writing to the console and either ignoring the error or returning early.
Updated the version number in package.json
> Add video support

- android/src/main/java/com/imagepicker/ImagePickerModule.java
Further testing #91 on 4.1 I ran into this exception:
```
E/AndroidRuntime( 4176): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime( 4176): com.facebook.react.bridge.ObjectAlreadyConsumedException: Receiving map already consumed
E/AndroidRuntime( 4176): 	at com.facebook.react.bridge.WritableNativeMap.putString(Native Method)
E/AndroidRuntime( 4176): 	at com.imagepicker.ImagePickerModule.launchImageLibrary(ImagePickerModule.java:216)
E/AndroidRuntime( 4176): 	at com.imagepicker.ImagePickerModule$1.onClick(ImagePickerModule.java:114)
```
I think the issue is that the callback is triggering even though the activity doesn't exist (prob on a different thread?). I confirmed this is the case because `onActivityResult` was being called with result cancel, so RN received the callback with …
> Tweak activity not found handler

- android/src/main/java/com/imagepicker/ImagePickerModule.java
Previous discussion: https://github.com/marcshilling/react-native-image-picker/pull/88
Here instead of just rejecting images without a path we actually create a new temporary file and copy from whatever URI was returned to the image intent. Tested this handles the `content://` URI in 4.4+.
> Handle case where we can't extract the image path in Android (v2)

- ios/UIImagePickerManager.m
containsString is an iOS8+ method and as such crashes on iOS7. Using
rangeOfString fixes that.
> Fix iOS7 crash

- android/src/main/java/com/imagepicker/ImagePickerModule.java
According to the readme for options `takePhotoButtonTitle` and `chooseFromLibraryButtonTitle` you can "specify null or empty string to remove this button"
This PR allows these options to be set to null. Tested with RN 0.19.0.
> Android: Add null checks for options

- ios/ImagePickerManager.m
Hello,
Here is a very simple implementation of the `durationLimit` option for iOS using [`picker.videoMaximumDuration`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImagePickerController_Class/#//apple_ref/occ/instp/UIImagePickerController/videoMaximumDuration)
This would probably close #115.
> Add duration limit option to iOS

- android/src/main/java/com/imagepicker/ImagePickerModule.java
When images are too large on our nicer Android devices, our image orientation is incorrect. From what I learned from [this article](http://voidcanvas.com/whatsapp-like-image-compression-in-android/), the correct orientation is restored, and the `angle` option is still regarded. 
I tested on both a phone that had this issue and one that didn't. 
Hopefully the code is sound - I don't code in Java, really.
> reorient image on image resize

- ios/ImagePickerManager.m
Add origURL to the returned object. This is a reference to the asset library handle of the original image. It can be passed to [react-native-color-grabber](https://github.com/bsudekum/react-native-color-grabber)
> Add ref to asset library version for color grabber

- README.md
- ios/ImagePickerManager.m
This PR provides the "mixed" option as suggested by @marcshilling in #200.
As a result, when the image picker `mediaType` is set to 
- *video*: You see only videos, and video props (like `durationLimit`) are set.
- *image*: You see only images.
- *mixed*: You see both, and video props are set.
The default behavior is, as before, to show only images.
Additionally, this PR fixes a counterintuitive feature of the `durationLimit` prop, as noted in the commit message: Previously, if "durationLimit" was set but "allowsEditing" was false, then the durationLimit would not be applied, which was counterintuitive.  Now setting the "durationLimit" automatically sets "allowsEditing" to true, so that the user can select a segment of the video if it's under the `videoMaximumDuration` property.  I think …
> Adds "mixed" option to "mediaType" for iOS

- README.md
- ios/ImagePickerManager.m
This adds an option under `storageOptions` called `cameraRoll` which, if set to `true`, will save the resulting cropped image to the iOS Camera Roll.
> Save to camera roll option

- android/src/main/java/com/imagepicker/ImagePickerModule.java
I'm getting a consistent crash on Android when using the camera to take a photo:
```
09-15 18:12:13.126  3323  3323 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: width and height must be > 0
09-15 18:12:13.126  3323  3323 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
09-15 18:12:13.126  3323  3323 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
09-15 18:12:13.126  3323  3323 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
09-15 18:12:13.126  3323  3323 E AndroidRuntime: 	at com.imagepicker.ImagePickerModule.getResizedImage(ImagePickerModule.java:625)
09-15 18:12:13.126  3323  3323 E AndroidRuntime: 	at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:425)
09-15 …
```
> Fix empty initialWidth and initialHeight [Android]

- ios/ImagePickerManager.m
Return video's reference url so that it can be used for sharing videos to Facebook via FBSDKShareVideo.
> Return video's reference url as origURL in response.

- android/src/main/java/com/imagepicker/ImagePickerModule.java
if maxWidth and maxHeight in options were large than initial size, will use the initial size.
> make the resized image not being stretched

- README.md
- android/src/main/java/com/imagepicker/ImagePickerModule.java
- ios/ImagePickerManager.m
Hey @marcshilling, awesome library!
This PR addresses #199 (issue was closed but not fixed).
For some devices (notably Samsung Galaxy S3, S5) and image will have a rotate value (90 deg) in the Exif data even if the image was never rotated.
So if you try to upload the image somewhere and then later grab it and render it, the image is rendered in the wrong orientation compared to the original.
I'm not sure if this needs to be handled at the library level but this PR simply at least passes that value as part of the response so if an image has a rotate value attached to it the client can decide how to handle (like transform the image 90deg to account for it)
Note: this hasn't been an issue for iOS but I figured I'd add it, I can remove it if that's easier
> Send originalRotation in response

- README.md
- ios/ImagePickerManager.m
This PR adds response fields for `fileName`, `latitude`, `longitude` and `timestamp` values on iOS. There are some caveats about when these fields are available in the response:
- `fileName` is always available for picked media and is available for media captured with the camera when `cameraRoll` and `waitUntilSaved` are both true (i.e. it needs to be in the filesystem to have a file name).
- `latitude` and `longitude` are available for picked media. Captured media doesn't get this metadata automatically, so some CoreLocation code can be added in the future to have this data for all cases.
- `timestamp` is available for picked media and is available for media captured with the camera when `cameraRoll` and `waitUntilSaved` are both true. Some more logic can be added in the future to get …
> Add fileName, latitude, longitude and timestamp response fields for iOS

- ios/ImagePickerManager.h
- ios/ImagePickerManager.m
- ios/RNImagePicker.xcodeproj/project.pbxproj
https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d moves header imports to `<React/*>`. This updates header include path and all imports so build works against react master (soon to be version 0.40.0).
TODO: Update examples when 0.40 is out.
> Update iOS RN header paths

- index.d.ts
The current TypeScript declaration exports the module as a `default` export. This is incorrect because the module is exported as CommonJS single export and should be consumed with `export = require(...)` TypeScript's construct.
This change addresses the issue by exporting the module with `export =`.
> Fix TypeScript module export

- android/src/main/AndroidManifest.xml
Problem was described in https://github.com/marcshilling/react-native-image-picker/issues/485.
Thanks @dsvictor94 for help.
> Fixed bug of getting authority for Android 5.1

- android/src/main/java/com/imagepicker/ImagePickerModule.java
Just updated minimal version API from 19 to 21 for working with FileProvider.
This fix covers crash from #485.
> Fixed minimal version for FileProvider

- android/src/main/java/com/imagepicker/ImagePickerModule.java
- This was broken by #496.
- Currently, the response object is empty, lacking the `didCancel` flag.
> Android: fix cancellation handling

- README.md
- android/src/main/java/com/imagepicker/ImagePickerModule.java
Fixes https://github.com/marcshilling/react-native-image-picker/issues/508.
Note: Either https://github.com/marcshilling/react-native-image-picker/pull/513 or this PR should be merged. We needed this feature right away for our app, so I needed to do the work anyway and figured I'd submit a PR.
Tested and verified on Android emulator and physical device.
@marcshilling please let me know if you'd like anything tweaked. Note that the temp image is never deleted after resizing, but that's an existing bug that isn't changed by this PR.
> Allow saving to camera roll on Android

- android/src/main/java/com/imagepicker/ImagePickerPackage.java
[`createJSModules` is now not required on Android](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8) from RN 0.47. I actually can't build an app on RN 0.47 without removing this method/@ovveride marker. There is similar PR (#649), but this one seems to be better for backwards compatibility.
> Remove createJSModules @overide marker - RN 0.47 compatibility

- android/src/main/java/com/imagepicker/utils/MediaUtils.java
This PR addresses the issue in https://github.com/react-community/react-native-image-picker/pull/428. If original image is big then Android device may run out of memory. The solution is to use subsampling if target maxWidth and maxHeight is much smaller than original. There is a side effect. If original can fit in memory, then using subsampling may cause lower image quality in resized version. I can add another check and only use subsampling when original is very big. But it's difficult to figure out what size will cause problems. I was able to load images >24M on a Galaxy S3 emulator. But others had trouble with smaller sizes.
Tested on Galaxy S3 emulator.
> [Android] Subsample image to save memory.

- android/src/main/java/com/imagepicker/ImagePickerModule.java
- android/src/main/java/com/imagepicker/permissions/PermissionUtils.java
**motivation**
I don't want to use `permissionDenied` option because
- I can't customize dialog styles (we have custom)
- back button doesn't work on this dialog
- no ios support 
And now I can't disable it
**test plan**
add here https://github.com/react-community/react-native-image-picker/blob/develop/Example/App.js#L28
`permissionDenied: null`
previous behaviour - app crashes
current behaviour - nothing is happening
> disable permission dialog when permissionDenied=null

- README.md
I was experiencing errors when trying to use a freshly taken photo due to `fileName` being undefined even when `storageOptions.waitUntilSaved` set to `true`. Then I came across the original PR #394 for this functionality which states that both `cameraRoll` AND `waitUntilSaved` need to be `true` for `fileName` and `timestamp` to be available for captured media.
This PR is a small change to the README to make this information easier to find for others, as I noticed issues such as #576.
> Update documentation for storageOptions.waitUntilSaved

- android/src/main/java/com/imagepicker/ImagePickerModule.java
some old phone do have this null issue when connect it's storage to a computer.
when connect it's storage to a computer.
the adb outputs:
java.lang.NullPointerException: file
at android.net.Uri.fromFile(Uri.java)
at com.imagepicker.utils.RealPathUtil.compatUriFromFile(RealPathUtil.java:25)
at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:253)
at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:203)
...
after null check the code works fine.
> null checker for some old phones

- android/src/main/java/com/imagepicker/ImagePickerModule.java
Provide workaround for Android bug on Kitkat (api level 19) to grantUriPermission to allow the camera to save photos
Built locally and tested on an Android KitKat device.
> Add support for KitKat (API level 19)

- android/src/main/java/com/imagepicker/utils/MediaUtils.java
Instead of duplicating the entire image in memory with
ByteArrayOutputStream.toByteArray(), write to the FileOutputStream without copying.
getResizedImage() often fails with OOME for larger images. See this stacktrace:
```
D/ERROR   ( 1993): java.lang.OutOfMemoryError: Failed to allocate a 5861516 byte allocation with 4274626 free bytes and 4MB until OOM
D/ERROR   ( 1993):      at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:122)
D/ERROR   ( 1993):      at com.imagepicker.utils.MediaUtils.getResizedImage(MediaUtils.java:182)
D/ERROR   ( 1993):      at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:453)
D/ERROR   ( 1993):      at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:256)
D/ERROR   ( 1993):      at …
```
> Avoid copying image data when saving and close the stream!

- README.md
Links to interactive graph showing the downloads trend of the package. 
Link here: https://npmcharts.com/compare/react-native-image-picker?minimal=true
Previously it linked to npmjs.org, but the "npm package" badge to its left already links to the same place.
Only changes the README.md, no testing required
> Link downloads badge to npmcharts.com

- .gitignore
- android/src/main/AndroidManifest.xml
- android/src/main/java/com/imagepicker/FileProvider.java
If multiple AndroidManifest.xml files specify FileProviders (e.g. the app, a library like react-native-image-picker), you may receive compilation errors when these AndroidManifest.xml files are merged due to conflicts in fields such as `android:authorities` and `android:resource`.
This occurs when multiple AndroidManifest.xml files specify a `android.support.v4.content.FileProvider`. To avoid the conflict, we subclass `android.support.v4.content.FileProvider` and then we refer to our subclass in the AndroidManifest.xml file to avoid the conflict.
This solution is described here: http://stackoverflow.com/a/41550634
I think this might be related to some of the discussion in #485.
Also, I added .vscode/ to .gitignore.
Adam Comella
Microsoft Corp.
> Avoid conflicting with other FileProviders

- android/src/main/java/com/imagepicker/ImagePickerPackage.java
While generating build getting below error:
node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerPackage.java:34: error: method does not override or implement a method from a supertype
@Override
^
1 error
:react-native-image-picker:compileReleaseJavaWithJavac FAILED
> Error while generating build.

- android/src/main/java/com/imagepicker/ImagePickerModule.java
Fixes the compatibility issue between React Native Navigation and React Native Image Picker in terms of checking for `PermissionAwareActivity`
Tests are horribly inadequate and should probably generally be fixed.
> Fix permission issue related to React Native Navigation permanently

- android/src/main/java/com/imagepicker/media/ImageConfig.java
call: ImagePicker.launchCamera for an Android 7 device.
camera launches succcessfully.
Crash message:
Tried to read an int but got non-integral double.
> Fix runtime crashe for Android 7.

- README.md
Especially considering this is a file that must be edited manually, good idea to have the full path.
> Specify full path to AndroidManifest.xml

- ios/ImagePickerManager.m
This fixes warnings that appear when targeting 32-bit architectures (iPhone 4S for example), the warnings are as follows:
1. `Implicit conversion loses integer precision: 'long long' to 'unsigned long'` (2 occurrences)
- `malloc` expects an `unsigned long`. `NSUInteger` in 32-bit architectures is an `unsigned long` where in 64-bit it is a `unsigned int`, it makes more sense to cast to `NSUInteger` explicitly.
2. `Implicit pointer to integer conversion returning 'NSNumber *' from a function with result type 'BOOL' (aka 'signed char')` (1 occurrence)
- This could introduce subtle bugs if any method depends on this result since we're casting an object to a BOOL. This will perform an existence check and `@NO` is an NSNumber object that is not nil so it'll always return `YES`.
- This was also …
> [iOS] Fix Xcode value conversion warnings

- android/src/main/java/com/imagepicker/ImagePickerModule.java
when multiple time image picker open is clicked doOnCancel() function cause app crash.
updated to handle case when callback is null.
when user click on open picker multiple times then on closing those popup it app was crashing.
> Update ImagePickerModule.java to fix multiple tap on upload image button crash

- android/src/main/java/com/imagepicker/ImagePickerModule.java
Fix a crash when launching either `launchCamera` or `launchImageLibrary` directly after having denied permissions and hitting OK on permissionDenied dialog. 
- Launch picker using `launchImageLibrary`
- Deny permissions
- Relaunch using `launchImageLibrary` with `permissionDenied` options specified
- Hit "I'm sure" button on permissionDenied dialog (or whatever text it was configured for)
Expected: dialog closes
Actual: crash due to missing callback
> Set this.callback before permissionsCheck so that permissionDenied dialog doesn't crash when trying to call the callback

- android/src/main/java/com/imagepicker/ImagePickerModule.java
On BTV-W09(HUAWEI)  Android 7.0 device, I only use ReactMethods(launchImageLibrary、launchCamera), start to request camera permission, and have camera permission, at last when exec listener callback,it doesn't do private methods，due to this.callback is null.
###Scenario 1
On BTV-W09(HUAWEI)  Android 7.0 device don't authorize camera permission
1. In js code ,ImagePicker.launchCamera(options, (response) => {});
2. start to request camera permission;
3. agree to get camera permission;
4. don't open camera;
###Scenario 2
On BTV-W09(HUAWEI)  Android 7.0 device have authorized camera permission
1. In js code ,ImagePicker.launchCamera(options, (response) => {});
2. open camera;
> since Android6.0, start to request permission, and fail to open camera

- docs/Install.md
Used the example in the install.md but got rejected in app store due to Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage.
The permission request alert should specify how your app will use this feature to help users understand why your app is requesting access to their personal data.
To hinder other people from getting their binary rejected, a note has been added to this section.
*What existing problem does the pull request solve?*
The pull request solves the problem of binaries getting rejected in app store due to not specifying how the app will use their personal data.
> Add note for NSCameraUsageDescription

- docs/Install.md
Fixed file name of `RNImagePicker.a` to `libRNImagePicker.a` in documentation.
I don't think it requires tests.
> Fix lib name in doc

- ios/ImagePickerManager.m
Fix a warning regarding assignment of `NSDictionary` (options) to `NSMutableDictionary` (self.options).
I don't think it requires tests...
> Fix iOS build warning

- ios/ImagePickerManager.m
I need to use `imageFileType` option in order to convert HEIC images to PNG. However, the invocation of `stringValue` crash, since `imageFileType` is already a string.
With `imageFileType` set to `png`
With `imageFileType` not set
> Remove crashing invocation of “stringValue” on iOS

- ios/ImagePickerManager.m
Fixes #818 which explains in more detail the rationale behind this change
1. Launch image picker via `Select a Photo` and tap `Choose from Library...`
2. Verify the permissions prompt appears as normal
3. Ensure that tapping "Ok" lets you access Photos as per normal
1. Launch image picker via `Select a Photo` and tap `Choose from Library...`
2. Verify the permissions  prompt appears as normal
3. Ensure that tapping "Cancel" does not let you access Photos
1. Launch image picker via `Select a Photo` and tap `Choose from Library...`
2. Verify no permissions prompt appears
3. Ensure that selecting a Photo works as normal
Ensure that the compiler macros work for both Xcode 9 (which has iOS 11 SDK) and all others below.
> [iOS] Update permissions flow for iOS 11 UIImagePickerController

- android/src/main/java/com/imagepicker/media/ImageConfig.java
See #972 . testOnImmutable fails due to NPE, and the test failure prevents `./gradle build` or `./gradle assembleRelease` from completing.
Previously failing test:
Test passes after change:
The only downside I can think of is that if a user were to somehow inadvertently pass a null argument to `withOriginalFile()` it would go uncaught, but the @Nullable annotation and `testOnImmutable()` seem to suggest that this is intentional.
> #972: change ImageConfig.withOriginalFile() to address testOnImmutable failure

- index.d.ts
This allows users of the library to get access to the types that the library uses to annotate their code. For example, it allows this pattern:
```javascript
import ImagePicker, { ImagePickerOptions } from "react-native-image-picker";
const options: ImagePickerOptions = {
noData: true
};
ImagePicker.openImagePicker(options);
```
I have also added the `ImagePicker` prefix to the interfaces to make it easier to distinguish them from other `Options` interfaces.
This can be tested by using the library with TypeScript and using the new types. I have tested this manually on my machine by modifying the type definitions in the `node_modules/react-native-image-picker/index.d.ts` file.
> Export the interfaces in TypeScript

- docs/Install.md
Documentation fix. 
`react-native link` does this already, but the steps in the manual installation steps still uses the old keyword.
> Change `compile` to `implementation`

- android/src/main/java/com/imagepicker/ImagePickerModule.java
`mixed` value for mediaFile config attribute was supported only on IOS. On Android you could either select images or videos but not both. 
This pull request maintains the Android side to support this value. By now the user, on Android, can pick images or videos or both. This pull request fixes this issue [789](https://github.com/react-native-community/react-native-image-picker/issues/789). The proposed solution is inspired by @pmella16 [comment](https://github.com/react-native-community/react-native-image-picker/issues/789#issuecomment-497558162).
I have tested the change on physical device Lenovo A1000.
> Add mixed support on Android

- ios/ImagePickerManager.m
iOS doesn't need permissions for picking a single image. See more https://stackoverflow.com/a/46594741.
We currently have an issue with this library, that if we want to select a single image, we need to bother the user with it, which is unnecessary. 
Permissions are notoriously hard to test, so this is something that needs to be done manually.
> iOS doesn't need permissions for picking a single image

- ios/ImagePickerManager.m
Fixes an issue present on iOS where the user is presented with a dialog requesting permission to view their images. The issue here is that `fetchAssetsWithALAssetURLS:options` requires the users permission. However, this method has been deprecated for quite some time. So, in this PR, I am pulling the `PHAsset` reference from the provided `info` dictionary that is passed into `didFinishPickingMediaWithInfo:`.
If the target is not running iOS 11 or later, I fall back to the old method of gathering permissions and using Photo Kit.
On devices running iOS 11 or later, users are not presented with a dialog requesting permissions.
On devices running iOS 10 or earlier, users will be presented with a system dialog requesting permissions to view images stored on their device.
> FIX - Issue #1252 - User is presented with permission request after callback has been executed

- android/src/main/java/com/imagepicker/ImagePickerModule.java
- [ x] Explain the **motivation** for making this change.
- [ x] Provide a **test plan** demonstrating that the code is solid.
- [ x] Match the **code formatting** of the rest of the codebase.
- [x ] Target the `master` branch, NOT a "stable" branch.
When picking images on android, files with names that have a space in them cause the response.type to be null. This bug causes the image attachment process to unexpectedly fail. These code changes were proposed in #1176 but haven't been placed in a pull request.
I have tested this change on an S7. Using the original version, I received a null response file type when choosing an image that has a space in its name, and after these changes, I received the correct file type. I …
> Fix for bug causing null file type on android (#1176)

- ios/ImagePickerManager.m
iOS 13 beta is not allowing the `moveItemAtURL` command to execute which may cause trimmed clips to fail based on permission.
Instead of moving the file, copy it.
Attempting to access a trimmed video clip on device is failing based on permissions for iOS 13 beta.
Instead of affecting the source file with a `move`, instead `copy` it.
To test, select a video clip from the library that was been trimmed on an iPhone running iOS 13 beta or greater.
An example fetch in JS could be: 
```
async showImagePicker () {
ImagePicker.showImagePicker({
mediaType: 'video',
noData: true,
permissionDenied: {
text: 'To choose and change profile and survey imagery.'
},
title: 'Select …
```
> Copy file instead of move

- android/src/main/java/com/imagepicker/ImagePickerModule.java
When accessing the camera for the first time only permission for the camera is requested.
This results in that the camera won't open on Android. 
The permission for writing to external storage is also required to launch the camera.
Related issues: #1286 #1290
Since there is no functional changes no new tests where added. All existing tests passes.
> Add write permission check when accessing camera android

- android/build.gradle
- android/gradle.properties
- android/src/test/java/com/imagepicker/testing/ImagePickerModuleTest.java
With Java 9 (and later) the unit tests fails with:
`java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader`.
Issue has been solved by upgrading RoboElectric and related test libraries.
Related issues #1121 #1142 
Existing android unit tests are still working, executed with Java 10.
> test: Make tests work with >=Java9 by upgrading libraries

- android/src/main/java/com/imagepicker/utils/MediaUtils.java
On several devices when trying to decode and resize the image (see #579), it will failed and return null value for image configuration. This patch will fix this behavior, instead of returning null value when failed to resize the image, use the original image configuration.
TODO
> Fix failure delivering result info #579

- android/gradle.properties
remove The option 'android.enableUnitTestBinaryResources' is deprecated
which is removed from gradle 6, The current default is 'false'
to allow the build using gradle 6
> remove deprecated gradle option

- README.md
Fixes the non-existent package name in `README.md` which is misleading and can sometimes be confusing.
> Fix wrong package name in README

- react-native-image-picker.podspec
The latest Xcode 12 fails to build when a module does not depend on `React-Core` directly. This change is necessary for all native modules on iOS. For details please see: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Xcode 12 is not building without this change.
1. Build an App with Xcode 11.x. Result: The app builds.
2. Build an App with Xcode 12. Result: The app will not build when depending on `React`.
3. Build an App with Xcode 12 with the PR changes applied. Result: The app builds.
A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See …
> fix: Xcode 12 compatibility

- android/build.gradle
Should fix https://github.com/react-native-image-picker/react-native-image-picker/issues/1458
> Remove unnecessary buildToolsVersion

- android/src/main/AndroidManifest.xml
- android/src/main/java/com/imagepicker/ImagePickerProvider.java
Should fix https://github.com/react-native-image-picker/react-native-image-picker/issues/1443#issuecomment-719743390
FYI, fixes just that particular comment, not the issue
> Fix: FileProvider class name conflict during manifest merger

- README.md
- android/src/main/java/com/imagepicker/ImagePickerModule.java
WRITE_EXTERNAL_STORAGE is not required for all cases. More info https://developer.android.com/training/data-storage
> Fix: Android permission check

- src/types.ts
Passing a `quality` option to the `launchImageLibrary` function shows a TypeScript error– since the `quality` option is currently only part of `CameraOptions` and not `ImageLibraryOptions`.
From my testing and usage– it looks like setting `quality: 0.3` when I call `launchImageLibrary` is working as intended. (I just have to add a ts-ignore in my project for now)
Version: `react-native-image-picker@3.0.0-vnext.4`
> fix(typescript): move quality from CameraOptions to ImageLibraryOptions

- android/src/main/java/com/imagepicker/ImagePickerModule.java
data.getData() works in my android devices but may be not all android camera applications support it, hence use cameraCaptureURI like we do for image capture.
fixes https://github.com/react-native-image-picker/react-native-image-picker/issues/1497
> Fix:Uri null error in some cases when video captured from camera

- package.json
Fix "Cannot find module 'react-native-image-picker' or its corresponding type declarations."
Fix types path to react-native-image-picker
> Fix: Types path not found

- android/src/main/java/com/imagepicker/ImagePickerModule.java
- android/src/main/java/com/imagepicker/Utils.java
- android/src/main/res/xml/imagepicker_provider_paths.xml
Now we don't delete files on every call, instead it will be handled by
Android OS. So people can expect to save the Uri and use it in later
session unless android clears the cache.
Make a copy of image file picked from gallery into internal storage for
later access. We don't copy videos picked from android gallery, so the uri 
wont persist sessions.
Now the implementation is same in iOS and Android, except for handling
of videos in android where videos picked from gallery are not duplicated. Which needs further discussion.
> Change directory where temporary files are stored to cache directory

- package.json
Fix for Cannot find module 'react-native-image-picker' or its corresponding type declarations. #1554
This fixes the issue 'Cannot find module 'react-native-image-picker' or its corresponding type declarations.' #1554 
Tested fine after changing `types` path.
> fix: wrong types path (#1554)

- src/index.ts
The library exits quietly logging error only on the native side when there is no callback function.
Like the issue https://github.com/react-native-image-picker/react-native-image-picker/issues/1589
Showing proper errors then and there should help library users self diagnose and fix error, instead of opening an issue.
> Show error and return when there is no callback function

- android/src/main/java/com/imagepicker/ImagePickerModule.java
Set type for intent instead of using URI to select image picker application. Now video and image picker intent uses same technique.
Should also fix #1613 (I still don't know if its valid error since I was not able to reproduce)
> Refactor how image picker intent is created

- android/src/main/java/com/imagepicker/ImagePickerModule.java
Best practice is to give read and write permission to content uri before sending to other apps.
> fix: add the correct permissions to the camera intent

- android/src/main/java/com/imagepicker/ImagePickerModule.java
- example/android/build.gradle
The solution is based on android docs
https://developer.android.com/training/package-visibility/use-cases
This should solve issues related to target api 30
closes #1587 #1658 
@Johan-dutoit
> Support android target api 30

- android/src/main/java/com/imagepicker/ImagePickerModule.java
Thanks in advance for taking a look. The product I work on uses react-native-image-picker. We would like to hook directly into these REQUEST_LAUNCH codes, but newer versions of this package don't expose them publicly anymore. I looked at the change that took them from public to private, and there didn't seem to be an explicit reason for the change. This change just makes them public again.
Just a minor change to make it easier for consuming apps to use these codes. Just making the 4 codes public.
> Make REQUEST_LAUNCH codes public

- README.md
- android/src/main/java/com/imagepicker/Options.java
- android/src/main/java/com/imagepicker/Utils.java
- ios/ImagePickerManager.m
- ios/ImagePickerUtils.m
- src/index.ts
- src/types.ts
This adds the architecture for iOS and Android to optionally offer the ability to include exif data with the selected photos. The requires iOS library permissions, hence `includeExif` defaults to `false`.
These changes will be released to several thousand users in our production application via our fork.
> Added ability to include exif data for iOS and Android

- ios/ImagePickerManager.m
What existing problem does the pull request solve? https://github.com/react-native-image-picker/react-native-image-picker/issues/1541
Right now I'm looking for general thoughts on whether this is an acceptable fix. I pulled it from the PHPickerController changes made to react-native-image-crop-picker.
Looking for recommendations here. So far I've been testing on the app I've been developing on that benefitted from this fix.
TODO:
[1]: …
> fix: photo selection in simulator on M1 macs

- android/src/main/java/com/imagepicker/Utils.java
- [  ] Provide a **test plan** demonstrating that the code is solid.
From #1699, I believe it is not safe to close the issue as latest code the report has already taken into `NullPointerException` with a more broad `RuntimeException`. Anyway, I find that it can be more stronger by instead of returning null (in `resizeImage` method which would trigger NPE in the first place), we can simply return the original uri.
I am not really sure if I can have a concrete test plan for this one-line change. It is a simple improvement to the existing codebase.
> fix(android): return the original 'uri' instead of null when resizeImage has failed

- README.md
- src/index.ts
Easier API for those who want to work with promises instead of callbacks. I have found myself moving 'promisifying' code across multiple projects which use this library.
New additions so only basic testing is needed as there is no risk of regression. We have ran tests within out application from our fork: https://github.com/Qeepsake/react-native-image-picker
> feat(api): added methods to launch the image picker and camera as promise 

- ios/ImagePickerManager.m
Fixes: #1670
The file name of videos on iOS hasn't been present in their asset objects, as it has for photos. This fixes that.
> feat(ios): Add `fileName` to video assets

- android/src/main/java/com/imagepicker/Utils.java
- "Unsupported file type" error was not thrown when mimeType could not be found (i.e. ICO files). Closes #1734 
- Exif data was trowing error when trying to run `SimpleDateFormat(...).parse(...)` on a null object (seems like a lot of photos on Android don't include exif say if they have been edited using an different app or downloaded from internet). Closes #1874
> fix(issues): fixes #1734 and #1874 by throwing and catching errors correctly

- README.md
- android/src/main/java/com/imagepicker/Utils.java
- android/src/main/java/com/imagepicker/VideoMetadata.java
- src/types.ts
Returns the bitrate of the video on Android
Could not get unit tests to run, but I did run the example app and ensured the bitrate is returned when selecting a video on Android
Retest since updates:
> feat(android): return video bitrate on Android

- ios/ImagePickerManager.m
Fixes #1742 where the app crashes on iOS 13 when picking a video.
Did some additional investigation on this issue to the cause and additionally into why it caused a fatal crash and found two things. 
1. On iOS 13.5 a NSError is set to the error variable `moveItemAtURL` while on iOS 14+, the error is set to Nil. The current check on the error `if (error)` matches incorrectly and ends up returning nil from the function when it should instead proceed. The original PR for this issue corrected this conditional error check. 
2. The part of this issue that resulted in a fatal crash to the app is because the `self.callback` method requires an "errorMessage", which in the particular path resulted in the error of `error.localizedFailureReason` being nil. The React Native error handler threw errors …
> fix(videos): videos not working on iOS 13 and throwing a fatal crash when selected

- README.md
- android/src/main/java/com/imagepicker/ImageMetadata.java
- android/src/main/java/com/imagepicker/Metadata.java
- android/src/main/java/com/imagepicker/Utils.java
- android/src/main/java/com/imagepicker/VideoMetadata.java
- ios/ImagePickerManager.m
- ios/ImagePickerUtils.h
- ios/ImagePickerUtils.m
Added the following properties to both Android and iOS for video:
- Added datetime (timestamp) to be returned for videos on iOS and Android.
- Added width/height (dimensions) to be returned for video on iOS and Android.
NOTE: I introduced and ImageMetadata class and a Metadata parent class which can be used to extend metadata on images and videos going forward, and should make it easier to add stuff such as returning `long`/`lat`. Will follow up this work sometime in the future and move stuff like Image orientation / dimensions to be accessed via the Exif class.
Tested on our production application both iOS and Android.
> feat(metadata): added width, height and datetime to video for iOS and Android

- ios/ImagePickerManager.m
There was an issue causing file not to be copied over to the temp directory which we have seen in Sentry for a while in out application i.e. `File 'file:///var/mobile/Containers/Data/Application/A7CB430B-F16F-47FC-8EEC-D63C95D867F9/tmp/F42EBD2C-F353-4289-A5D3-4879294BFA0B.jpg' does not exist.`. This was because apple was returning the following ID for some Live Photos `com.apple.private.live-photo-bundle` (not sure why this was the case as I was unable to detect any clear pattern) and we were not handling photos with that ID.
On other note if NSData / Image is null after running `loadFileRepresentationForTypeIdentifier` we should really be throwing an error, but that can a follow up PR.
This PR should catch all IDs which contain `live-photo-bundle`.
Closes #1905 #1836 (maybe more 🤷‍♂️)
> fix(live-photos): issue with non-existent file path when copying live photos with ID com.apple.private.live-photo-bundle

- android/src/main/java/com/imagepicker/ImagePickerModule.java
Action popup always show when picking up an image.
When two or more image library apps are installed in users device, then this action popup contains those apps and ask us which one to use. Normally Android takes care of this and asks if you want to save your option. 
Function `createChooser` always enforces this action to being taken.
Here is an example of it 
And here is how it gets when removing `createChooser` function
> fix(android): actions being saved when open launchImageLibrary

- CONTRIBUTING.md
The contributing guide is outdated, the "principal" branch is called "main", not master.
Only docs, no need to test.
> docs: use main branch in CONTRIBUTING guide

- android/src/main/java/com/imagepicker/Utils.java
fix issue - https://github.com/react-native-image-picker/react-native-image-picker/issues/1934
After this small fix, in cache folder exist only one resized image.
> fix: remove original image file after resizing image

- android/src/main/java/com/imagepicker/ImagePickerModule.java
- ios/ImagePickerManager.m
We have noticed several crashes due to a RuntimeException for our App on multiple Android devices. The StackTrace given in the Playstore console is as follows.
```
java.lang.RuntimeException:
at android.app.ActivityThread.deliverResults (ActivityThread.java:5471)
at android.app.ActivityThread.handleSendResult (ActivityThread.java:5512)
at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:149)
at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:103)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2386)
at android.os.Handler.dispatchMessage (Handler.java:107)
at android.os.Looper.loop (Looper.java:213)
at …
```
> fix(1944): fix runtime exceptions in ImagePickerModule

- ios/ImagePickerManager.m
This PR fixes a bug described in [#1977 ]. This bug was introduced in [this PR](https://github.com/react-native-image-picker/react-native-image-picker/pull/1948).
The variable `photoSelected` was never reset in the case of the function `launchCamera` as it was with the function `launchImageLibrary`.
This issue causes the function `launchCamera` to never resolve on the second call. This PR fixes this.
Steps to reproduce:
Execute the following twice.
1. Call `launchCamera` and select an image.
2. Console.log the resolved promise either using await or a promise chain.
Prior fix:
- The promise is resolved on first `launchCamera`
- The promise is not resolve on second `launchCamera`
Post fix:
`launchCamera` does resolve as expected on second call (or on every subsequent call of course). …
> fix(1977): fix reset photo selected on ios

- ios/ImagePickerManager.m
On ios, when users select multiple images, this library seems to return array of assets in a random order.
As the PHPickerViewController API preserves the user selection order, it is preferred to keep the order consistent also in this library.
Current behavior. It does not preserve the user selection order.
https://user-images.githubusercontent.com/25456520/163591074-0a3ba496-e608-47eb-887f-4c0303100cc6.mov
Fixed behavior. It preserves the user selection order.
https://user-images.githubusercontent.com/25456520/163591140-e1e22ebb-eb2f-46f0-9d56-942df9e144c6.mov
> fix: let multi-selection return assets in a consistent order on ios

- example/ios/Podfile.lock
- example/ios/example/Info.plist
- example/src/App.tsx
- ios/ImagePickerManager.m
This PR fixes a bug described in [issue 1894](https://github.com/react-native-image-picker/react-native-image-picker/issues/1894).
the binary data returned by `UIImageJPEGRepresentation` and `UIImagePNGRepresentation` is much larger than
the original file.
this PR will use the original data first if user doesn't pass `maxWidth`, `maxHeight` and `quality`
prepare a image:
1. save the above png image in a device.
2. run example app in the device ( `Team` and `Bundle Identifier` may need to be configured first).
3. click `Select Image` to select the above image
4. compare `fileSize` in the screen with the value in the `Photo` ( or use `ls -l` to check the saved image size)
5. click `Take image` and compare the two values again
In addition,
there is an issue in the `react-native` library when …
> fix: the fileSize of the selected image is bigger than the origin one in ios

- README.md
- android/build.gradle
- android/src/main/java/com/imagepicker/ImagePickerModule.java
- android/src/main/java/com/imagepicker/VideoMetadata.java
Android 13 (codenamed Teramisu) introduces a new [Photo Picker AP](https://developer.android.com/about/versions/13/features/photopicker)I that doesn't require the app to access full media libraries. Going forward, the photo picker will be the recommended way to access the user’s photos and videos. It also provides the API to select a specific amount of image/video to be selected instead of any number.
- Follow [the doc](https://developer.android.com/about/versions/13/get) to setup Android 13 emulator
- Click Select Image, Select Video or mixed, and check if it pop up the new Photo picker UI
- Play with `0`, `1` and `3` values for `selectionLimit` to see if it correctly handles max, one and certain amount of limit cases.
- Test the same thing with Android < 13 device
(Currently there is …
> feat: add new PhotoPicker API for Android 13 Teramisu

- ios/ImagePickerManager.m
this PR solve this bug: #2022 
has described here: https://developer.apple.com/documentation/imageio/cgimagepropertyorientation?language=objc
the image from the camera could have an orientation different to the one that the user want to see :D
and you need to take it in account when you are copying the data
- run example app
- take a photo in portrait mode
- see that the photo has the correct orientation on the preview
- take a photo on landscape
- see that the photo has the correct orientation on the preview
> fix: take in account the image orientation when create a copy

- ios/ImagePickerUtils.m
Selecting HEIC files will return the original format which is in most cases not desired.
Selecting HEIC should get us the JPEG file format.
Changing the `preferredAssetRepresentationMode` from [PHPickerConfigurationAssetRepresentationModeCurrent](https://developer.apple.com/documentation/photokit/phpickerconfigurationassetrepresentationmode/phpickerconfigurationassetrepresentationmodecurrent?language=objc) to [PHPickerConfigurationAssetRepresentationModeAutomatic](https://developer.apple.com/documentation/photokit/phpickerconfigurationassetrepresentationmode/phpickerconfigurationassetrepresentationmodeautomatic?language=objc) will automatically select the appropriate format; for heic files we will get jpeg. This is also the behaviour of `UIImagePickerController`.
This way we will be …
> Change PHPicker preferredAssetRepresentationMode to Automatic

- src/types.ts
By factoring out an `interface OptionsCommon` that both interfaces extend, instead of having one extend the other minus a property. This seems cleaner, since the properties are now neatly organized into three groups:
- in common
- unique to ImageLibraryOptions
- unique to CameraOptions
This doesn't actually change either type, just how we structure their definitions, so I don't expect it to add or remove any type errors that TypeScript reports.
It also makes the TypeScript file a bit friendlier to conversion to Flow via TsFlower: https://github.com/gnprice/tsflower
-----
(See above)
Could we add a `yarn test` script that runs the TypeScript type checker? I'm not very familiar with how to operate TS (my project uses Flow …
> fix(types): Define CameraOptions and ImageLibraryOptions symmetrically

- ios/ImagePickerManager.m
If you select a `.bmp` image it will fail on iOS. This is due to the fact that `canLoadObjectOfClass:[UIImage class]` is not really image universal (i.e. does not support bmp and possibly other types).
We do use `hasItemConformingToTypeIdentifier` for videos and for the old image picker. It makes sense to use it here too for the new image picker (phpicker).
___
That being said, the fix is simply to swap this line
```java
if ([provider canLoadObjectOfClass:[UIImage class]]) {
```
with
```java
if ([provider hasItemConformingToTypeIdentifier:(NSString *)kUTTypeImage]) {
```
If you think the use of `canLoadObjectOfClass` is necessary we can extend the condition as follow:
```java
if ([provider canLoadObjectOfClass:[UIImage class]] || [provider hasItemConformingToTypeIdentifier:(NSString …
```
> Changed the way we detect images in iOS

- example/src/App.tsx
- ios/ImagePickerManager.mm
This fixes a hang that occured on mp4 conversion when capturing a new video.
Also fixes the filename.
> fix(mp4): no longer hang on export when taking a video

- android/src/main/java/com/imagepicker/ImageMetadata.java
- android/src/main/java/com/imagepicker/Utils.java
- android/src/main/java/com/imagepicker/VideoMetadata.java
While working on solving #2138, @huextrat noticed that the various streams and descriptors were never closed.
This is leaking a lot of resources.
I converted those to try-with-resources syntax, so they are automatically closed after the block ends.
I tested various files and videos with the example app, and did not notice any issue.
I also enabled `StrictMode` on the example app (see https://wh0.github.io/2020/08/12/closeguard.html) and it no longer detects non-closed resources.
> Fix android leaks

- android/build.gradle
This removes the breaking change required to support the RN 0.73 and will support both older and newer versions.
> fix(android): 🐛 only set namespace if gradle 7 or newer is used

- android/src/main/AndroidManifest.xml
v5.6.0 is no longer building for React-Native 0.68.
After upgrading react-native-image-picker from 5.4.2 to 5.5.0 my app no longer builds because of the following issue: `error: cannot find symbol new ImagePickerPackage()`
This issue was introduced here: 
https://github.com/react-native-image-picker/react-native-image-picker/commit/4584d7b0df4b859a73fc70aa2f17ba643885427f
This pr will fix these bugs :
- https://github.com/react-native-image-picker/react-native-image-picker/issues/1688
- https://github.com/react-native-image-picker/react-native-image-picker/issues/2154
Build android
Using react-native 0.68.2
Gradle 7.3.1
buildToolsVersion 33
compileSdkVersion 33
targetSdkVersion 33
minSdkVersion 24
kotlinVersion 1.7.0
Use `patch-package` with the following update
```
diff --git …
```
> fix(android): support rn version 0.68

- android/src/main/java/com/imagepicker/Utils.java
In some cases the [`getExtensionFromMimeType`](https://android.googlesource.com/platform/frameworks/base/+/0ea8c8a7c060873ef94e8aa8a637bc90852777d1/core/java/android/webkit/MimeTypeMap.java#151) may return `null`, in which case the generated file would lack the extension. This PR adds fallback to rely on the extension when it happens.
I wasn't able to make a reproducible example to showcase the problem, however, it emerged during the migration of the Expensify app to the new architecture. [We've been using the patch](https://github.com/Expensify/App/blob/a9c5bcbf52ee7c368c5390d58ea489d6b4f53d6e/patches/react-native-image-picker%2B5.3.1.patch#L25-L39) for a while and didn't see any problems with it.
> Add fallback to getting extension from filename

- android/src/main/java/com/imagepicker/Utils.java
- [ x] Explain the **motivation** for making this change.
- [x ] Provide a **test plan** demonstrating that the code is solid.
- [x ] Match the **code formatting** of the rest of the codebase.
- [x ] Target the `main` branch, NOT a "stable" branch.
the width / height returned by the library is swapped if the image is on portrait mode on some device (tested with Sony zx1 compact, and see also in some samsung device)
this because the library do not look on the image orientation when computing the w/h this is a problem also if the set the maxHight/Width since you are currently compare maxWidth with height and maxHeight with width
fix #1901 #1689
run the example app, take the photo on portrait, check that the height > width …
> correctly handle orientation on android

- README.md
Corrected iOS video permission key names in the README.
Issue: 'NSCameraUsageDescription' is a duplicate.
Before: NSCameraUsageDescription & NSCameraUsageDescription
After : NSCameraUsageDescription & NSMicrophoneUsageDescription
Since this is a modification to the README documentation, there are no tests.
Link to '[NSMicrophoneUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nsmicrophoneusagedescription)'
> docs(readme): Modify video permission key name

- src/platforms/native.ts
This pull request addresses the issue of a typographical error in our codebase. The incorrect variable name 'nativeImagePicler' has been corrected to 'nativeImagePicker'. This correction improves the readability and accuracy of the code, ensuring that our naming conventions are consistent and clear. It also prevents potential bugs and errors that might arise from using an incorrectly named variable in future developments. This small yet significant change contributes to the overall health and maintainability of the project.
No test is needed
> fix: correct typo in variable name nativeImagePicler

- ios/ImagePickerManager.h
I use your package for the example of my react-native library in react-native 0.73.
When I build my example with the new architecture enable, I face the issue:
```
▸ Compiling ImagePickerManager.mm
❌  /Users/thibault/StudioProjects/api.video-reactnative-uploader/example/node_modules/react-native-image-picker/ios/ImagePickerManager.h:32:43: no type or protocol named 'RNImagePickerSpec'
@interface ImagePickerManager : NSObject <RNImagePickerSpec>
^
```
Full logs is available here: https://github.com/apivideo/api.video-reactnative-uploader/actions/runs/7142227360/job/19451072582#logs
I think the reason it fails it is because the interface should implement …
> Failed to build when `RCT_NEW_ARCH_ENABLED=1`

- ios/ImagePickerUtils.mm
- react-native-image-picker.podspec
When trying to build on iOS with new architecture enabled, user face the following error 
Given that we're importing `ImagePickerManager.h` inside `ios/ImagePickerUtils.mm`, which imports `RNImagePickerSpec.h`, we need to rename this file to `.mm`
After this change a different error shows up regarding `ld` not finding the following simbols:
```
ld: Undefined symbols:
_OBJC_CLASS_$_PHAsset, referenced from:
in libreact-native-image-picker.a[2](ImagePickerManager.o)
_OBJC_CLASS_$_PHPhotoLibrary, referenced from:
in libreact-native-image-picker.a[2](ImagePickerManager.o)
_OBJC_CLASS_$_PHPickerConfiguration, referenced from:
in libreact-native-image-picker.a[3](ImagePickerUtils.o)
_OBJC_CLASS_$_PHPickerFilter, referenced from:
in libreact-native-image-picker.a[3](ImagePickerUtils.o) …
```
> fix(ios): Fix support for new architecture on react-native 0.74

- android/build.gradle
React Native 0.74.1 added [the minimum SDK version bump to 23](https://reactnative.dev/blog/2024/04/22/release-0.74#android-minimum-sdk-bump-android-60). This PR tends to add the same, making sure the previous 21 is intact.
Run example app on android.
> fix: change minSdkVersion for RN 0.74.1

- android/src/main/java/com/imagepicker/VideoMetadata.java
Timestamp for video files on Android were incorrect, offsetted by the user's device timezone.
The code previously dropped the timezone information (which was always GMT from my testing), but did not include it in the string date when parsing it, resulting in this GMT date being parsed with the current timezone.
With this fix, it is now correctly parsed as a GMT date.
I also updated the format to avoid having to replace the `T` as this can be processed correctly by the date parser.
This has been tested in the example app with multiple video files from real devices having date information using a timezone.
After those changes, the timestamps are correct.
> fix(android): video timestamps have the wrong timezone

- react-native-image-picker.podspec
After installing version 7.1.2, when I run the iOS project it won't compile since it complains of undefined classes
It is related to this issue https://github.com/react-native-image-picker/react-native-image-picker/issues/2318
It compiles the iOS project in latest version
I don't know how you make it work in your environment but if these frameworks are missing it won't work
> fix(ios): missing required frameworks

- src/platforms/web.ts
The `cancel` input event is not handled, so if the user attempts to cancel the picking process, the promise that the library returns will never be resolved. Most likely this will result in app code that is stuck waiting for the user to make a selection.
- Invoke `launchImageLibrary` on web
- Cancel the file selection dialog that appears
- Notice that the promise from `launchImageLibrary` is not resolved, and never will be
> fix(web): Cancelling image picker does not resolve the promise

- ios/ImagePickerUtils.mm
Fix the video quality setting not working in mixed mode on iOS
Solve the following issues:
* #2256 
* #2161 
* #2123 
* #1908 
Tested changes on Simulator and real iPhone devices.
> fix: video quality setting not working in mixed mode on iOS

- README.md
- android/src/main/java/com/imagepicker/ImagePickerModuleImpl.java
- android/src/main/java/com/imagepicker/Options.java
- example/src/components/DemoResponse.tsx
- src/platforms/native.ts
- src/types.ts
The Android camera app has an option to store both JPEG and RAW (DNG format) files for each picture. When this option is enabled, both versions of the image are shown to the user (but without any indication of the file format, so the users sees every image twice).
This new options allows you to restrict the allowed MIME types, for example `restrictMimeTypes: ['image/jpeg', 'image/heic', 'image/png']`.
On Android 13 (new Photo Picker), only the matching files are displayed, no more duplicates.
On older Android versions, every file is still displayed in the file explorer, but non-matching files are grayed and can not be selected.
This option can not be implemented on iOS, as the API only allows you to filter on predefined types (images, videos, slow-mos…).
I used `restrictMimeTypes: …
> feat(android): permit to specify a list of allowed mime-types
