README.md, UIImagePickerManager.m, package.json
Hi Marc,
I changed a bit the component operation to make it more extensible and better prepared for an increase of more parameters and i18n.
Changed the input method and the first callback parameter to improve the ability to have more options in the future and let developers customize the titles of buttons.
Best regards.
=> Method signature changed and callback params for improve functionality and extensibility for i18n and more smart feedback component

UIImagePickerManager.m
This provides the URL for the image captured from the camera. Creating a Base64 String from the images takes a lot of time.
A better way to do this was to have a url returned.
=> adding URL for the image captured from the camera

UIImagePickerManager.m
* remove constant COMPRESSION_QUALITY
=> Add quality as an option

UIImagePickerManager/UIImagePickerManager.m
I've reworked this a bit, if you like the changes please accept the PR.  I don't think it negatively affects any current functionality.  
1)  Fixed it so that it works inside a RN Modal as well as outside one.
2)  Added support for maxWidth and maxHeight options that will downscale the image if needed before returning.
3)  Save the selected image to tmp directory and return a file:// style image url rather than an assets-library url.  This allows you to do things like upload it from objective c later with less trouble.  Also necessary for the downscaling.  
Apologies for the formatting changes, automatically done by my editor...
=> Modal fix and max dimensions

README.md, UIImagePickerManager/UIImagePickerManager.h, UIImagePickerManager/UIImagePickerManager.m
Hi!  I wanted to be able to launch the camera / image library directly, skipping the popup dialog.
This code lets you choose between the Camera or the Image Library.
Thanks for sharing this library!
=> Optionally Bypass Alert Dialog (Directly Launch Camera/Library)

react-native-image-picker.podspec
Handy for us Cocoapods users, thanks!
=> Add podspec

Android/src/main/java/com/imagepicker/ImagePickerModule.java, README.md
Hello :)
- maxWidth
- maxHeight
- quality
(work like iOS)
Those are probably the last options that i will implement, the version is stable, the code can probably be improved but it's efficient.
If you could publish it to npm it would be really great !
=> Android maxWidth maxHeight and Quality

ios/UIImagePickerManager.m
apps (like Giphy) can save animated gifs to the camera roll, but
attempting to resize gifs in the picker destroys them, so we need
to just copy the raw data.
=> add support for animated gifs

android/src/main/java/com/imagepicker/ImagePickerModule.java
When starting intents to get a photo from the camera or photo album.
=> handle ActivityNotFoundException

android/src/main/java/com/imagepicker/ImagePickerModule.java
- Use a temp file for the resized images. Otherwise they are displayed under the "pictures" folder within my app files
- Fix path for resized images, make sure it points to the resized file
=> Resize tweaks

ios/UIImagePickerManager.m
The skipBackup step needs to be moved to the end, after the media file has been created / moved, or else iOS writes an error message about it to the console.
Also, moving video files to the destination path isn't working for files picked from the image picker (it only seems to work for video captured with the camera).
=> Fix iOS bugs with skipBackup and moving video files to the Documents folder.

ios/ImagePickerManager.m
In my app, I am displaying a React Native Alert in the response callback from RNImagePicker. This works fine on iPhone and iPod touch. But on iPad, the Alert doesn't show, and I get a warning in the Xcode console:
`Warning: Attempt to present <UIAlertController: 0x7ad6ba00> on <UIImagePickerController: 0x7ac63c00> whose view is not in the window hierarchy!`
I can reproduce this in iPads with different models and in the iPad simulator. The Alert doesn't show and this warning only occurs if you display an React Native Alert in the response callback in iOS on iPad. Everything works as intended on iPhone & iPod touch devices.
I believe what is happening is that the React Native Alert iOS implementation sets a reference to the UIImagePickerController as its popoverViewController, but this …
=> Invoke response callbacks after UIImagePickerController dismiss animation has completed

README.md, ios/ImagePickerManager.m, package.json
Add image file size to the response
=> Add image file size to the response

android/src/main/java/com/imagepicker/ImagePickerModule.java
https://github.com/marcshilling/react-native-image-picker/issues/178
=> [Android] Add latitude, longitude and date taken at to image picker response

android/src/main/java/com/imagepicker/ImagePickerModule.java
https://github.com/marcshilling/react-native-image-picker/issues/227
=> [Android] fix crash after using the camera

android/src/main/java/com/imagepicker/ImagePickerModule.java, index.js, ios/ImagePickerManager.m
fixes #246 
misc:
removed Android's default cancel button title to make it symmetric
disallowed null/empty cancelButtonTitle in JS
=> set default opts for showImagePicker from javascript

README.md
I thought the inclusion of a Platform check in the sample code might be helpful to those new to react-native
Thanks for the lib ❤️ 🚀 😄
=> Set source based on Platform

android/src/main/java/com/imagepicker/ImagePickerModule.java, ios/ImagePickerManager.m
1.Don't save photo when it is selected from assets library.
2.Save video on ios.
3.fix bug: in some android versions save a photo to SD card doesn't appear in gallery app.（need fully test on other android version）
=> ios save video,android bug when save photo/video

android/build.gradle, android/src/main/java/com/imagepicker/ImagePickerModule.java
Be sure to merge this after 0.33.0 is released
=> Support RN 0.33.0

README.md
=> Badges and Positioning content (#334)

Example/ios/Example/Info.plist
- NSLocationWhenInUseUsageDescription is not right
- NSPhotoLibraryUsageDescription is right
=> corrected word spelling

README.md, ios/ImagePickerManager.m
To get callback from 'storageOption effect'.
If waitUntilSaved is true, I get the response when 'extra image is saved'.
=> Added storageOptions.waitUntilSaved

android/src/main/java/com/imagepicker/ImagePickerModule.java, android/src/main/java/com/imagepicker/utils/ButtonsHelper.java, android/src/main/java/com/imagepicker/utils/ReadableMapUtils.java, android/src/main/java/com/imagepicker/utils/RealPathUtil.java, android/src/main/java/com/imagepicker/utils/UI.java, package.json
This is a part of "big tidy".
I've moved `showImagePicker` logic to separated files. Nothing was broken.
=> Refactoring Android source code

Example/package.json, package.json
=> Fixed dependencies

README.md
As discussed in https://github.com/marcshilling/react-native-image-picker/issues/508.
=> Clarify which folders will be used with `storageOptions`

index.js.flow
There type script definitions for project, but no one for Flow
Will be cool to have it
You should try to use this PR with Flow
```
import type { Response as PickerResponse } from 'react-native-image-picker';
```
=> Add Flow support

ios/ImagePickerManager.m
Modify the way to get root view controller. 
On the one hand the older way wasn't work in some cases， on the other hand RN has already provide a better function to do so.  We can use it directly.
=> Update ImagePickerManager.m, Modify the way to get root view controller.

index.js.flow
Per documentation:
> The first arg is the options object for customization (it can also be null or omitted for default options)
Therefore the first parameter should be allow to be null or omitted in type definition.
Also it's not necessary to specify `callback` return type as `void`.
Tested with our own project, and also with Try Flow:
```js
showImagePicker({cameraType: 'front'}, () => {});
showImagePicker(null, () => {});
showImagePicker(() => {});
showImagePicker(async() => {});
showImagePicker(1, () => {}); // expect error
showImagePicker(); // expect error
```
https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1LgJ4YqgBKKAzlgHaWkC8oA3oqO6AMYCulusAWwBC3XPxoAuUH2wBLGgHMA3Gw4ATWWoDCAQxqcU0KQCNYsaCj0qOoFNmw4pM+ctXs1O3Dqe …
=> Fix Flow type for optional parameter

README.md
Width & height dimensions are only returned for photos
Missing information
Does not apply
=> Documentation fix on response object

README.md
This step is not an optional step, but was below the optional heading and this tripped me up and I spent a day debugging not being able to upload images from the device. Hoping to save someone else a day or more of unnecessary debugging. :)
It makes it clear that this is part of Android setup and is not an optional step.
N/A
=> Move non-optional step above the (optional) header

README.md
Make the codes in README.md bug-free.
The example code cannot compile.
N/A just document change
=> Added missing comma in README.md

README.md
They were getting long and wrapping.
=> Move README badges below title.

README.md, package.json
=> Merge develop into master

ios/ImagePickerManager.m
Fixes #470 
On iOS, Call `showImagePicker` with options: 
```
storageOptions: {
skipBackup: true,
cameraRoll: true
}
```
After you take photo, photo should be saved to camera roll with correct metadata so that it doesn't show rotated in it.
=> Fixed wrong image orientation when saved to camera roll

android/src/main/java/com/imagepicker/media/ImageConfig.java
=> Fix Android to bypass GIF image compression

index.js
=> Fix spreaded export

README.md, docs/API-Reference.md, docs/Install.md, docs/Reference.md
=> Refactor docs

.prettierrc, README.md, docs/Install.md, docs/Reference.md, index.js, package.json
=> Configure Prettier

index.d.ts
The ImagePickerOptions type was missing the permission options.
N/A
=> Add ImagePickerPermissionOptions typings

src/index.ts
The default text color for picker does not match system default
Fixes #1206
Before: 
After:
=> use system default picker text color

ios/ImagePickerManager.m
UIKit complains when  ImagePickerController not being called from main thread. 
To fix this I've added this method recommended in the docs:
http://facebook.github.io/react-native/docs/native-modules-ios.html#threading
#1199 (updated)
Not need, no business logic changed, all test pass.
=> Make sure the calls are execute on the main thread

src/internal/types.ts
It adds a missing TypeScript property.
Since there is no functional changes no new tests where added. All existing tests pass.
=> style: #1424 Add missing originalRotation property

README.md
=> Add reference to version 3.x.x to master readme

src/index.ts
=> fix(image-library): call the correct native function

android/src/main/java/com/imagepicker/ImagePickerModule.java, android/src/main/java/com/imagepicker/Utils.java
Fixes https://github.com/react-native-image-picker/react-native-image-picker/issues/1461
=> Fix: Check activity request code

android/build.gradle, android/src/main/java/com/imagepicker/ImagePickerModule.java, android/src/main/java/com/imagepicker/Utils.java
Fixes 
https://github.com/react-native-image-picker/react-native-image-picker/issues/1466
https://github.com/react-native-image-picker/react-native-image-picker/issues/1338
And should fix orientation related issues on android
=> Fix: image orientation issue on android

README.md, android/src/main/java/com/imagepicker/ImagePickerModule.java, android/src/main/java/com/imagepicker/Utils.java
Should fix https://github.com/react-native-image-picker/react-native-image-picker/issues/1474
Need to release a new version.
=> Fix: Android weird camera permission

README.md
=> Fix: Update readme to show link to previous version docs

README.md, android/src/main/java/com/imagepicker/ImagePickerModule.java, android/src/main/java/com/imagepicker/Options.java, ios/ImagePickerUtils.m, src/index.ts, src/types.ts
=> Feat: Add durationLimit option for video capture

package.json
=> fix: added main entry point

ios/ImagePickerManager.m
=> Add import conditional to allow package to compile with Mac Catalyst

android/src/main/java/com/imagepicker/Options.java
This defaults the video quality to high (1) and if the value is anything other than high (barring empty), then it will fallback to low (0).
Closes GH-1546
=> fix(video-quality): 🐛 map video quality to relevant int

ios/ImagePickerManager.m
=> Remove unused import.

README.md, android/src/main/java/com/imagepicker/ImagePickerModule.java, android/src/main/java/com/imagepicker/Options.java, android/src/main/java/com/imagepicker/Utils.java, ios/ImagePickerUtils.m, src/index.ts, src/types.ts
=> feat(camera): option to select front or back

README.md, android/src/main/java/com/imagepicker/ImagePickerModule.java, android/src/main/java/com/imagepicker/Utils.java
This should fix issues which wanted file uri to work easily with other libraries.
=> refactor: return fileuri instead of contenturi in android

src/types.ts
I've noticed a mistake on the types.ts file at `ErrorCode`. I believe that this value should be `others` instead of `other`?
=> fix(types): correct error code for others

README.md, android/src/main/java/com/imagepicker/Utils.java, ios/ImagePickerManager.m, src/types.ts
This feature has been requested by few users, closes issues like #1655
=> Return video duration in response

package.json
It currently points to an invalid URL
n/a
=> Fix homepage URL in package.json

README.md, android/src/main/java/com/imagepicker/ImagePickerModule.java, android/src/main/java/com/imagepicker/Options.java, android/src/main/java/com/imagepicker/Utils.java, example/src/App.js, ios/ImagePickerManager.m, ios/ImagePickerUtils.h, ios/ImagePickerUtils.m, src/types.ts
Closes #1527 
People can use this PR and test.
Release a beta version. @Johan-dutoit
=> Support mixed media type for launchImageLibrary

android/src/main/java/com/imagepicker/Utils.java, example/src/App.js
Fixes #1712 
This is an Android issue.
=> Fix saveToCamera crash when target SDK 30

README.md, android/src/main/java/com/imagepicker/ImagePickerModule.java, android/src/main/java/com/imagepicker/Options.java, android/src/main/java/com/imagepicker/Utils.java, example/src/App.tsx, ios/ImagePickerManager.m, ios/ImagePickerUtils.m, src/index.ts, src/types.ts
- Fixed the resize issue in android
- Fixed gif image issue in iOS
- Also rename `allowMultiple` to `selectionLimit` since iOS supports providing an integer value
- Updated Readme
@Johan-dutoit @rpander93 Please review and test.
=> Fix issue in multiple file selection

ios/ImagePickerManager.h, ios/ImagePickerManager.m
=> Fix: In iOS 14 didCancel: true is not returned when picker is cancelled via swipe gesture

android/src/main/java/com/imagepicker/ImagePickerModule.java
=> fix(selectionLimit): 🐛 use ACTION_GET_CONTENT for multiple image selection instead of ACTION_PICK

src/types.ts
Typings are incorrect, and will cause potentially crashing apps if code is implemented incorrectly :-).
The typings are incorrect, caused a bug in our production app. 
See Motivation
Implement gallery picker, cancel picking see no assets if you log or try to use the field
=> fix: assets is actually optional

android/src/main/java/com/imagepicker/Utils.java, ios/ImagePickerManager.m, ios/ImagePickerUtils.h, ios/ImagePickerUtils.m, src/types.ts
Mime types were marked as TODO. This PR adds support for them. 
Select media and observe the `assets` array - it should have the correct mime type in the `type` key.
=> Add type to asset objects

example/ios/Podfile.lock, ios/ImagePickerUtils.m
=> fix(video): 🐛 apply quality to both recordings and image picking

README.md, android/src/main/java/com/imagepicker/Utils.java, example/ios/Podfile.lock, example/src/App.tsx, ios/ImagePickerManager.m, ios/ImagePickerUtils.h, ios/ImagePickerUtils.m, src/types.ts
ID can be used to detect if the user has selected the image or video again, useful when app supports multiple images or videos to be uploaded
Android:
iOS:
=> feat(asset): return id of asset for iOS and Android

README.md, example/src/App.tsx, ios/ImagePickerUtils.m
Support taking photos and videos on iOS.
```js
launchCamera({
mediaType: 'mixed'
});
```
<div>
</div>
=> Support mixed option for iOS

android/src/main/java/com/imagepicker/VideoMetadata.java
`MediaMetadataRetriever` can directly return the video dimensions, no need to extract a frame for this.
I was troubleshooting #2138 and noticed that if I commented the dimension-extraction code, it would work fine with 30+ videos.
I am not familiar with Android, but a quick search showed that the video dimensions can be extracted like the other metadata. Switching to the metadata extractor fixed the ANRs I reported in the linked issue.
I am not sure why it was done this way initially this way, maybe @lukebrandonfarrell can provide some context (author of the initial #1891 PR introducing this code)
I tested this using the example app, selection up to 40 videos on my Android 13 phone. This returned the correct dimensions for the files, and did not crash nor cause an ANR.
I did not test in …
=> fix(android): improve video dimensions extraction

.circleci/config.yml, example/ios/Podfile.lock, example/package.json, example/yarn.lock, package.json, yarn.lock
=> chore(example): 🔧 update deps

.circleci/config.yml, package.json, yarn.lock
Updates semantic release to a newer version
=> chore(ci): 🔧 update semantic release

package.json, yarn.lock
=> Release v7

src/types.ts
Without this change, I get a typescript error.
No test is needed
=> Add missing attribute (originalPath)

ios/ImagePickerManager.mm
Resolves #2159
Resolves #2127
Related change: https://github.com/react-native-image-picker/react-native-image-picker/pull/1728
=> fix: In iOS 14 didCancel: true is not returned when camera is cancelled via swipe gesture

android/build.gradle, android/gradle.properties
=> fix(2330): Update compileSdkVersion and targetSdkVersion
